### ISSUE TITLE
Elasticsearch basic authentication support

### ISSUE THREAD

**Issue by ericslandry** [mattweber/es2graphite#18]
I added quick and dirty basic authentication support
[es2graphite.py.txt](https://github.com/mattweber/es2graphite/files/56049/es2graphite.py.txt)

Feel free to integrate it

**Comment by Ralnoc** [comment]
Could you do this as a PR? It is hard to review the changes and merge then as an attached text file.

**Comment by ericslandry** [comment]
Done. I should'of done this in the first place, but didn't have much time yesterday.
